# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
gem 'sinatra-cors', '~> 1.1'
gem 'twitter'

group :development do
  gem 'pry-byebug'
end

group :test do
  gem "rspec"
  gem "rack-test", require: 'rack/test'
end
